name: gdtestsite
favicon: null
layout_spectrum: 0.7436161909718066
typography_spectrum: 0.3609550010878593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9082487362902611
  lightness: 0.016051774146035314
  saturation: 0.15774293267168105
  rhythmicContrast: 0.4399147927761078
purpose: []
